version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/erp_db
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev && npm run dev"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mayur@#1201
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"